### PR TITLE
move the default output path to .nexus-prisma

### LINKED ISSUE #108: nexus-prisma types undefined when deploying to heroku
When deploying to heroku the app crashes with the error seen in the screenshot.
local build works without any problems.

#### Screenshot

Heroku-deployment-not-working

#### Description 

parts of my package.json file:

```json
"scripts": {
    "start": "node .build/api/app.js",
    "postinstall": "prisma generate",
    "build": "tsc",
},
"dependencies": {
    "@prisma/client": "2.27.0",
    "apollo-server": "^2.25.2",
    "aws-sdk": "^2.939.0",
    "bcrypt": "^5.0.1",
    "cuid": "^2.1.8",
    "graphql": "^15.5.1",
    "graphql-middleware": "^6.0.10",
    "graphql-shield": "^7.5.0",
    "jsonwebtoken": "^8.5.1",
    "nexus": "^1.1.0",
    "nexus-prisma": "^0.30.0"
  },
 "devDependencies": {
    "typescript": "^4.3.5",
  },
```

### PR DESCRIPTION
**Pull request by AhmedElywa**
closes #108

moving the default output path to `node_modules/.nexus-prisma` to fix the issue in some platforms and package managers rebuild the package files after the `prisma generate` command generates our code

### CODE REVIEW

File: src/generator/generate.ts [hunk 1]
```diff
@@ -21,7 +21,8 @@ export const generateRuntimeAndEmit = (dmmf: DMMF.Document, settings: Settings.G
 
   const declarationSourceFile = ModuleGenerators.TS.createModule(dmmf, settings)
 
-  if (settings.data.output.directory === 'default') {
+  // comment this code because we generate only in on path
```
Comment (AhmedElywa) [inline src/generator/generate.ts:25]: We need to figure out a way to support ESM.
My recommendation is we generate a CJS by default, as I found in the Prisma Client, and the user can change this with custom settings.
We were only generating a CJS if the user selected a custom path to generate code in.

File: src/generator/ModuleGenerators/TS.ts [hunk 2]
```diff
@@ -126,11 +126,7 @@ export const renderTypeScriptDeclarationForDocumentModels = (
       //
       //
 
-      import type { Settings } from ${
-        settings.data.output.directory === 'default'
-          ? `'../generator/Settings'`
-          : `'nexus-prisma/dist-cjs/generator/Settings'`
-      }
+      import type { Settings } from 'nexus-prisma/dist-cjs/generator/Settings/index'
```
Comment (AhmedElywa) [inline src/generator/ModuleGenerators/TS.ts:129]: I don't know why I must add `index` at the end, or it will break.

File: src/generator/generate.ts [hunk 3]
```diff
@@ -103,28 +107,17 @@ const getOutputSourceDir = (params: { esm: boolean }): string => {
...
   } else {
-    /**
-     * At this point in the code we don't know if the CLI running is the CJS or ESM version.
-     * If it is the CJS version and we're doing an ESM build then we need to adjust the __dirname value.
-     */
-    outputSourceDir = Path.join(
-      params.esm ? __dirname.replace('dist-cjs', 'dist-esm') : __dirname,
-      '../runtime'
-    )
+    outputSourceDir = Path.join(__dirname, '../../../../node_modules/.nexus-prisma')
```
Comment (AhmedElywa) [inline src/generator/generate.ts]: Found that after like 5 hours of testing and debugging.
We must go four steps back because if we use `Yalc` in the testing, we need one level more to be in the project dir then we need to go inside `node_modules.`

File: tests/e2e/kitchen-sink.test.ts [hunk 4]
```diff
@@ -88,8 +88,8 @@ beforeEach(() => {
       graphql: '^15.5.0',
       nexus: '1.1.0',
       prisma: '^3.5.0',
-      'ts-node': '^9.1.1',
-      'ts-node-dev': '^1.1.6',
+      'ts-node': '^10.8.1',
```
Comment (AhmedElywa) [inline tests/e2e/kitchen-sink.test.ts]: I faced a typescript error in the testing and fixed them by upgrading the `ts-node` package. 

```
typescript: '^4.2.3',
```
getting the last version that maybe have an issue with the other package, so maybe we need to fixed it

File: scripts/default-index.d.ts [hunk 5]
```diff
@@ -1,12 +1,9 @@
...
+/* eslint-disable @typescript-eslint/no-explicit-any */
 /**
  * If you're seeing this it means that you have not generated Nexus Prisma.
  *
  * Nexus Prisma is partly a generated library. Before using it you must run its generation step.
  *
  * To run its generation step simply run Nexus reflection like you normally would.
  */
-export const PleaseRunPrismaGenerate = runtimeProxy
+export declare const PleaseRunPrismaGenerate: any
```
Comment (andrewicarlson) [inline scripts/default-index.d.ts]: Why are we removing this additional typing? (eg removing `runTimeProxy` and replacing it with `any`)

Could we use a more specific type than `any` here?

File: scripts/default-index.js [hunk 6]
```diff
@@ -1,8 +1,4 @@
-/* eslint-disable @typescript-eslint/no-explicit-any */
-/* eslint-disable @typescript-eslint/no-unsafe-return */
-
-import { noop } from 'lodash'
-
+const lodash = require('lodash')
```
Comment (andrewicarlson) [inline scripts/default-index.js]: Are the changes in this file necessary? They seem materially the same except we're requiring the whole lodash package instead of just the methods we need (`noop`)

Combined with `scripts/default-index.d.ts` above I'm not sure why we need changes in either of these files.

File: src/cli/nexus-prisma.ts [hunk 7]
```diff
@@ -27,7 +27,7 @@ process.env.DEBUG_HIDE_DATE = 'true'
 generatorHandler({
   onManifest() {
     return {
-      defaultOutput: Path.join(__dirname, '../runtime'),
+      defaultOutput: Path.join(__dirname, '../../../../node_modules/.nexus-prisma'),
```
Comment (andrewicarlson) [inline src/cli/nexus-prisma.ts]: This looks fragile. Can we find a way to get to `node_modules` without relatively traversing the tree so much?

File: src/generator/ModuleGenerators/JS.ts [hunk 8]
```diff
@@ -98,12 +98,7 @@ export const createModule = (params: {
         }
       `
 
-  const importSpecifierToNexusPrismaSourceDirectory =
-    gentimeSettings.data.output.directory === 'default'
-      ? `..`
-      : esm
-      ? `nexus-prisma/dist-esm`
-      : `nexus-prisma/dist-cjs`
+  const importSpecifierToNexusPrismaSourceDirectory = esm ? `nexus-prisma/dist-esm` : `nexus-prisma/dist-cjs`
```
Comment (andrewicarlson) [inline src/generator/ModuleGenerators/JS.ts:101]: Does this PR intend to remove the ability for people to set a custom output directory?

File: src/generator/ModuleGenerators/TS.ts (hunk 2 above)
Comment (andrewicarlson) [reply src/generator/ModuleGenerators/TS.ts:129]: Are you overriding `--moduleResolution` somewhere? Resolution to a file named `index` is a node thing

File: scripts/postinstall.js [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+
+const copyFile = promisify(fs.copyFile)
+const mkdir = promisify(fs.mkdir)
+
+ensureEmptyDotPrisma()
+
+async function ensureEmptyDotPrisma() {
+  try {
+    const inTheNodeModules =
+      __dirname.endsWith('/node_modules/nexus-prisma/scripts') ||
```
Comment (andrewicarlson) [inline scripts/postinstall.js]: Should this be `/node_modules/.nexus-prisma/scripts`?

File: scripts/postinstall.js [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+      __dirname.endsWith('/.yalc/nexus-prisma/scripts')
+    const dotNexusPrismaDir = path.join(
+      __dirname,
+      inTheNodeModules ? '../../../node_modules/.nexus-prisma' : '../.nexus-prisma'
```
Comment (andrewicarlson) [inline scripts/postinstall.js]: Is there a safer way to locate node modules than by doing this relative traversal?

File: src/generator/generate.ts (hunk 1 above)
Comment (andrewicarlson) [reply src/generator/generate.ts:25]: The Prisma Client allows users to set a custom output directory. Do we intend to break from that pattern in this PR?

**Review by andrewicarlson — CHANGES_REQUESTED** [review]

File: scripts/default-index.d.ts (hunk 5 above)
Comment (AhmedElywa) [reply scripts/default-index.d.ts]: the `runtimeProxy` type is `any`

this only be there before the developer run `prisma generate` and this content will change with the generated code

File: scripts/default-index.js (hunk 6 above)
Comment (AhmedElywa) [reply scripts/default-index.js]: This file is the init file of the generated file. This code is only used not to break the nexus code while we generate our types 
So these two files are not necessary.
What you have here is the compiled code from the CJS.

image

image

I only copied them to be ready for use.

File: src/cli/nexus-prisma.ts (hunk 7 above)
Comment (AhmedElywa) [reply src/cli/nexus-prisma.ts]: I added a comment to note why we need to do that https://github.com/prisma/nexus-prisma/pull/219#discussion_r889737189 
we have `yalc` in testing breaking paths

File: src/generator/ModuleGenerators/JS.ts (hunk 8 above)
Comment (AhmedElywa) [reply src/generator/ModuleGenerators/JS.ts:101]: No, at all, 
this is only how we export nexus-prisma code in the generated file.
It was using an internal path while our generated code was inside the package itself and using a full path if a user added a custom output path.
but now we moved the default path outside the package itself, so we don't need this statement

File: scripts/postinstall.js (hunk 9 above)
Comment (AhmedElywa) [reply scripts/postinstall.js]: no the scripts inside the package itself to generate the `.nexus-prisma` folder

File: scripts/postinstall.js (hunk 10 above)
Comment (AhmedElywa) [reply scripts/postinstall.js]: I added a comment to note why we need to do that https://github.com/prisma/nexus-prisma/pull/219#discussion_r889737189 
we have `yalc` in testing breaking paths

**Comment by AhmedElywa** [comment]
> The Prisma Client allows users to set a custom output directory. Do we intend to break from that pattern in this PR?

No, users can customize their Prisma client output path

File: scripts/default-index.js (hunk 6 above)
Comment (andrewicarlson) [reply scripts/default-index.js]: >So these two files are not necessary.

If the changes aren't necessary I think we should omit them from this PR?

File: src/cli/nexus-prisma.ts (hunk 7 above)
Comment (andrewicarlson) [reply src/cli/nexus-prisma.ts]: Yeah that's what I'm saying – this looks pretty fragile. Could we use something like `require.resolve()` to  find the module rather than traversing the tree?

Comment (AhmedElywa) [reply src/cli/nexus-prisma.ts]: Thanks for your advice. I already used it. Thanks for your help. I didn't know about `require.resolve` usage.

File: src/generator/ModuleGenerators/TS.ts (hunk 2 above)
Comment (jasonkuhrt) [reply src/generator/ModuleGenerators/TS.ts:129]: I think it is because ESM requires file paths. It does not support Node resolution algorithm. But Maybe this is something else, because if this were ESM related I would expect that the file extension is required too.

File: src/generator/generate.ts (hunk 3 above)
Comment (jasonkuhrt) [reply src/generator/generate.ts]: General empathy: Yep this kind of stuff is _super_ painful.

**Comment by jasonkuhrt** [comment]
I just saw this in my GH notifications. Exciting stuff, I'll try to look this week. I think this overall direction will be a great step forward for the project (albeit plumbing that users don't even know they appreciate but that's just a testament to how important this stuff is). ⭐️ 🙌

File: package.json [hunk 11]
```diff
@@ -70,7 +71,9 @@
     "release:pr": "dripip pr",
     "release:canary": "dripip preview",
     "release:stable": "dripip stable",
-    "prepublishOnly": "yarn build"
+    "prepublishOnly": "yarn build",
+    "generate": "node scripts/postinstall.js",
```
Comment (jasonkuhrt) [inline package.json]: Is this a lifecycle script?

File: src/generator/generate.ts (hunk 1 above)
Comment (jasonkuhrt) [reply src/generator/generate.ts:25]: IIUC we're formally revisiting ESM support later so not worrying about it now seems OK.

I can try to do that later this week or next.

**Review by jasonkuhrt — COMMENTED** [review]
Overall LGTM. Some parts I skimmed. I would say if I can consume a preview release of this in PDP without issue then 👍 from me :)

File: package.json (hunk 11 above)
Comment (AhmedElywa) [reply package.json]: for the build to happen we need to have the '.nexus-prisma' folder exist in our app so we need to run `yarn generate` to generate our output path.
I added this folder to the `.ignore` file.

iI took this way from prisma client 
image

File: src/generator/generate.ts (hunk 1 above)
Comment (andrewicarlson) [reply src/generator/generate.ts:25]: @jasonkuhrt yep, looking to formally support that soon https://github.com/prisma/nexus-prisma/issues/200#issuecomment-1112384600

File: package.json (hunk 11 above)
Comment (jasonkuhrt) [reply package.json]: Sounds like a new workflow thing to document in CONTRIBUTING?

Comment (AhmedElywa) [reply package.json]: If you are a new contributor and will run `yarn install` to contribute

this command will run and add the folder for you.

`"postinstall": "node scripts/production/postinstall.js"`

```
➜  nexus-prisma git:(output-path) yarn 
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
$ node scripts/production/postinstall.js
✨  Done in 17.00s.
```

If you are a user and the project is already installed on your PC you need to run `yarn generate`

`"generate": "node scripts/production/postinstall.js",`

Can I update the build command to be `"build": "yarn generate && yarn clean && tsc --build tsconfig.cjs.json tsconfig.esm.json",`

**Comment by jasonkuhrt** [comment]
@AhmedElywa I don't have time to try this out. Can you validate yourself if this is working or not on a project of your choosing. And if we can improve the e2e tests to answer this question that's better.

**Comment by AhmedElywa** [comment]
> @AhmedElywa I don't have time to try this out. Can you validate yourself if this is working or not on a project of your choosing. And if we can improve the e2e tests to answer this question that's better.

I already did a test with a project, and it's working well. Also, the tests are working good that's means everything is in its place.

I will take another look to see if I need to add another test.

**Review by jasonkuhrt — APPROVED** [review]
LGTM

@andrewicarlson if you want to take one more pass go for it otherwise let's merge. We'll have time to do more QA with the preview release.

**Review by andrewicarlson — APPROVED** [review]
